name: CICD Test of Docker Deployment
on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code    
          uses: actions/checkout@v4
        - name: SSH to Server and Deploy Docker Container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              cd /home/ubuntu/cicd_docker_test
              git pull origin main
              docker compose up -d --build